remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
nav:
  - name: 关于本站
    link: /blogs/README.html
  - name: 博客归档
    link: /blogs/home.html

